### PR TITLE
Refactor DockerHub samples to use multi-arch tags

### PR DESCRIPTION
**Pull request by MichaelSimons**
With the use of the image-builder tool to build and push the images to Docker Hub in conjunction with using multi-stage builds,  there is no longer a need for the DockerHub branch.  I am therefore proposing we use the dotnetapp-prod sample in the master branch as the sample we build and push to Docker Hub.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@richlander, @kendrahavens - any objections to removing the DockerHub branch and building the sample right from master?  I think this will help keep the contents on Docker Hub/Store up-to-date.  The only downside I see it that it adds some build related artifacts to the repo.

**Review by kendrahavens — APPROVED** [review]
I agree this will simplify keeping the DockerHub Readme up-to-date and make it more clear what we view is the main path we want to guide users on. Thank you for these improvements Michael!

**Review by crummel — APPROVED** [review]
LGTM.

**Comment by MichaelSimons** [comment]
Fixes #55

**Pull request merged**
