### PR TITLE
Add Preview version sample

### PR DESCRIPTION
**Pull request by richlander**

### CODE REVIEW

**Comment by MichaelSimons** [comment]
What is the thinking behind including a sample for the preview bits?  How did you decide to base the sample on rel-1.0.0-Preview2.1 versus rel-1.0.0?

**Comment by richlander** [comment]
There are really two scenarios at hand:
- LTS vs Current
- Stable v. Preview

My main motivation is demonstrating how to change the version number (MP and TFM). That's an important concept in p.j. Showing the version number change across the two different version aspect (Current assuming the default is LTS and Preview assuming the default is stable) is secondary. People will presumably want to try both of these.  One oddity is that it is a totally different concern than what the other samples are showing. 

I was guessing this about the two product series:
- rel-preview2.1 is 1.1 using p.j
- rel-1.0.0.0 is 1.1 using csproj

Is that right?

**Comment by MichaelSimons** [comment]
The reason I asked was just to make sure we weren't overwhelming people with samples and making it harder for customers to focus in on what they needed to get started. I see this sample as a secondary more advanced scenario.  Should we be distinguishing the advanced samples from the basic ones?

Regarding the two CLI `channels` we support.
- yes rel-1.0.0-Preview2.1 is p.j based using 1.1
- rel-1.0.0 is csproj based but not currently using 1.1.  I believe the next release (preview3) is not going to take 1.1.

**Comment by richlander** [comment]
Got it. That all makes sense. I'll make some changes to the root README.md to help this issue.

**Pull request merged**
