### PR TITLE
Update to utilize multi-step build feature

### LINKED ISSUE #50: Update samples to make use of multi-step Dockerfiles
This will simplify the steps to build the Dockerfiles as everything can be easily contained within the Dockerfile.

### PR DESCRIPTION
**Pull request by MichaelSimons**
Currently the multi-step build infra is only available with Docker Edge release 17.05. We will want to hold off merging this until the multi-step infrastructure is released in Stable.  I believe this will be 17.06.

fixes #50

### CODE REVIEW

**Review by kendrahavens — APPROVED** [review]
Holding off sounds good. This really cleans up the process!

**Comment by kendrahavens** [comment]
I believe Docker merged the multi-stage build functionality into their stable channel today! Let's merge these samples.

**Comment by MichaelSimons** [comment]
@kendrahavens - I updated the PR.  I needed to merge in the multi-arch changes that came on-board since the original creation of the PR.  I removed the `dotnetapp-current` sample as mentioned in #52 as well as updated the samples to all use 1.1.  Can you take a look please?

**Comment by kendrahavens** [comment]
The WriteLine for the dotnetbot say samples should be changed to 1.1 instead of 1.0 with the upgrade.

Everything else looks good.

**Comment by MichaelSimons** [comment]
@kendrahavens - Good catch - I fixed dotnetbot to emit the correct version of .NET Core.

**Pull request merged**
